services:
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: node-observability-otel
    ports:
      - "4317:4317" # grpc
      - "4318:4318" # http
      - "8888:8888" # prometheus metrics exposed by the collector
      - "8889:8889" # prometheus exporter metrics
      - "55678:55678" # opencensus
    volumes:
      - ./docker/otel/config.yaml:/etc/otel/config.yaml
    command: --config=/etc/otel/config.yaml
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    container_name: node-observability-prometheus
    volumes:
      - ./docker/prometheus/config.yaml:/etc/prometheus/config.yaml
    command: --config.file=/etc/prometheus/config.yaml
    ports:
      - "9090:9090"
    depends_on:
      - otel
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: node-observability-grafana
    ports:
      - "3001:3001"
    environment:
      - GF_SERVER_HTTP_PORT=3001
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - default

  zipkin:
    image: openzipkin/zipkin:3
    container_name: node-observability-zipkin
    ports:
      - "9411:9411"
    networks:
      - default

  opensearch-node1:
    image: opensearchproject/opensearch:1.3.20
    container_name: node-observability-op-node1
    environment:
      - cluster.name=node-observability-cluster
      - node.name=opensearch-node1
      - discovery-type=single-node
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_master_nodes=opensearch-node1
      - http.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch:/usr/share/opensearch/data
      - ./docker/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - default

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.0
    container_name: node-observability-op-dashboards
    volumes:
      - ./docker/opensearch/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    depends_on:
      - opensearch-node1
    networks:
      - default

  fluent-bit:
    image: fluent/fluent-bit
    container_name: node-observability-fluent-bit
    ports:
      - "24224:24224"
    volumes:
      - ./docker/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node-observability-app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - prometheus
    networks:
      - default

networks:
  default:
    name: node-observability
    external: false

volumes:
  grafana-storage:
    name: node-observability-grafana
    external: false
  opensearch:
    name: node-observability-opensearch
    external: false