global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'otel'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel:8889']
        labels:
          application: 'node-observability'

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          application: 'node-observability'

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          application: 'node-observability'